---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: presync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: presync-job
          image: ubuntu
          command: 
            - /bin/bash
            - -c
            - |
              echo "Integration testing Done"
              
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-job
  annotations:
    argocd.argoproj.io/hook: PostSync    
spec:
  template:
    spec:
      containers:
        - name: postsync-job-success
          image: ubuntu
          command: 
            - /bin/bash
            - -c
            - |
              apt update -y
              echo "*******************************************************************************************************************************************"
              apt upgrade -y
              echo "*******************************************************************************************************************************************"
              apt install curl -y
              echo "*******************************************************************************************************************************************"
              curl --version
              echo "*******************************************************************************************************************************************"
              

      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-fail-
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification-failed
        image: ubuntu
        command: 
            - /bin/bash
            - -c
            - |
              apt update -y
              apt upgrade -y
              apt install curl -y
              curl --version
              
      restartPolicy: Never
  backoffLimit: 2
